services:
  - type: web
    name: accessflow
    runtime: static
    buildCommand: npm install --registry=https://registry.npmjs.org/ && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
